<a href="https://colab.research.google.com/github/abhishekanand04/ML-Unsupervised-and-RecSys/blob/unsupervised/RS_Practical_Session.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Import Libraries
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

In [ ]:
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1' -O "movies.csv"
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR' -O "ratings.csv"
!wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h' -O "users.csv"

--2026-01-23 15:45:24--  https://drive.google.com/uc?export=download&id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1
Resolving drive.google.com (drive.google.com)... 142.251.108.101, 142.251.108.100, 142.251.108.138, ...
Connecting to drive.google.com (drive.google.com)|142.251.108.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1&export=download [following]
--2026-01-23 15:45:24--  https://drive.usercontent.google.com/download?id=1Q9UJtrN_v_dS-garl5gQ1I_SotGhye_1&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 192.178.142.132, 2607:f8b0:4023:80d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|192.178.142.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 515699 (504K) [application/octet-stream]
Saving to: ‘movies.csv’

movies.csv          100%[===================>] 503.61K  --.-KB/s    in 0.07s

2026-01-23 15:45:26 (7.15 MB/s) - ‘movies.csv’ saved [515699/515699]

--2026-01-23 15:45:26--  https://drive.google.com/uc?export=download&id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR
Resolving drive.google.com (drive.google.com)... 142.251.108.101, 142.251.108.100, 142.251.108.138, ...
Connecting to drive.google.com (drive.google.com)|142.251.108.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR&export=download [following]
--2026-01-23 15:45:26--  https://drive.usercontent.google.com/download?id=1HOFWUAMFlYbd-gk1B2IyV2-hXDZI7gKR&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 192.178.142.132, 2607:f8b0:4023:80d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|192.178.142.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2475052 (2.4M) [application/octet-stream]
Saving to: ‘ratings.csv’

ratings.csv         100%[===================>]   2.36M  --.-KB/s    in 0.1s

2026-01-23 15:45:29 (20.5 MB/s) - ‘ratings.csv’ saved [2475052/2475052]

--2026-01-23 15:45:29--  https://drive.google.com/uc?export=download&id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h
Resolving drive.google.com (drive.google.com)... 142.251.108.101, 142.251.108.100, 142.251.108.138, ...
Connecting to drive.google.com (drive.google.com)|142.251.108.101|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h&export=download [following]
--2026-01-23 15:45:29--  https://drive.usercontent.google.com/download?id=1b7_yRRBs3s3atp1WQHN2GU577vxY8u_h&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 192.178.142.132, 2607:f8b0:4023:80d::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|192.178.142.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 16784 (16K) [application/octet-stream]
Saving to: ‘users.csv’

users.csv           100%[===================>]  16.39K  --.-KB/s    in 0s

2026-01-23 15:45:31 (75.5 MB/s) - ‘users.csv’ saved [16784/16784]

In [ ]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [ ]:
movies.head(2)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [ ]:
ratings.head(2)

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807

## Make this in a regreesion problme

In [ ]:
m = movies.copy()

In [ ]:
m

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
10324,146684,Cosmic Scrat-tastrophe (2015),Animation|Children|Comedy
10325,146878,Le Grand Restaurant (1966),Comedy
10326,148238,A Very Murray Christmas (2015),Comedy
10327,148626,The Big Short (2015),Drama
10328,149532,Marco Polo: One Hundred Eyes (2015),(no genres listed)

In [ ]:
m['genres'] = m['genres'].str.split('|')
m

,movieId,title,genres
0,1,Toy Story (1995),"[Adventure, Animation, Children, Comedy, Fantasy]"
1,2,Jumanji (1995),"[Adventure, Children, Fantasy]"
2,3,Grumpier Old Men (1995),"[Comedy, Romance]"
3,4,Waiting to Exhale (1995),"[Comedy, Drama, Romance]"
4,5,Father of the Bride Part II (1995),[Comedy]
...,...,...,...
10324,146684,Cosmic Scrat-tastrophe (2015),"[Animation, Children, Comedy]"
10325,146878,Le Grand Restaurant (1966),[Comedy]
10326,148238,A Very Murray Christmas (2015),[Comedy]
10327,148626,The Big Short (2015),[Drama]
10328,149532,Marco Polo: One Hundred Eyes (2015),[(no genres listed)]

In [ ]:
m = m.explode('genres')
m

       movieId                                title              genres
0            1                     Toy Story (1995)           Adventure
0            1                     Toy Story (1995)           Animation
0            1                     Toy Story (1995)            Children
0            1                     Toy Story (1995)              Comedy
0            1                     Toy Story (1995)             Fantasy
...        ...                                  ...                 ...
10324   146684        Cosmic Scrat-tastrophe (2015)              Comedy
10325   146878           Le Grand Restaurant (1966)              Comedy
10326   148238       A Very Murray Christmas (2015)              Comedy
10327   148626                 The Big Short (2015)               Drama
10328   149532  Marco Polo: One Hundred Eyes (2015)  (no genres listed)

[23114 rows x 3 columns]

In [ ]:
m.head(7)

   movieId             title     genres
0        1  Toy Story (1995)  Adventure
0        1  Toy Story (1995)  Animation
0        1  Toy Story (1995)   Children
0        1  Toy Story (1995)     Comedy
0        1  Toy Story (1995)    Fantasy
1        2    Jumanji (1995)  Adventure
1        2    Jumanji (1995)   Children

In [ ]:
m = m.pivot(index='movieId', columns='genres', values='title')

In [ ]:
m

genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,Toy Story (1995),Toy Story (1995),Toy Story (1995),Toy Story (1995),NaN,NaN,NaN,Toy Story (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,Jumanji (1995),NaN,Jumanji (1995),NaN,NaN,NaN,NaN,Jumanji (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Grumpier Old Men (1995),NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Waiting to Exhale (1995),NaN,NaN,Waiting to Exhale (1995),NaN,NaN,NaN,NaN,NaN,NaN,Waiting to Exhale (1995),NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,Father of the Bride Part II (1995),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146684,NaN,NaN,NaN,Cosmic Scrat-tastrophe (2015),Cosmic Scrat-tastrophe (2015),Cosmic Scrat-tastrophe (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146878,NaN,NaN,NaN,NaN,NaN,Le Grand Restaurant (1966),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148238,NaN,NaN,NaN,NaN,NaN,A Very Murray Christmas (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
148626,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Big Short (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
149532,Marco Polo: One Hundred Eyes (2015),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
m = ~m.isna()

In [ ]:
m

genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,False,False,True,True,True,True,False,False,False,True,False,False,False,False,False,False,False,False,False,False
2,False,False,True,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False
4,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False,False,False
5,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146684,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
146878,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
148238,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
148626,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False
149532,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
m = m.astype(int)

In [ ]:
m

genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
146684,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
146878,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
148238,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
148626,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
149532,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
m.head(2)

genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [ ]:
r = ratings.copy()

In [ ]:
r

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [ ]:
r['hour'] = r['timestamp'].apply(lambda x : datetime.fromtimestamp(x).hour )

In [ ]:
r

        userId  movieId  rating   timestamp  hour
0            1       16     4.0  1217897793     0
1            1       24     1.5  1217895807     0
2            1       32     4.0  1217896246     0
3            1       47     4.0  1217896556     0
4            1       50     4.0  1217896523     0
...        ...      ...     ...         ...   ...
105334     668   142488     4.0  1451535844     4
105335     668   142507     3.5  1451535889     4
105336     668   143385     4.0  1446388585    14
105337     668   144976     2.5  1448656898    20
105338     668   148626     4.5  1451148148    16

[105339 rows x 5 columns]

In [ ]:
users = pd.read_csv('users.csv')

In [ ]:
r.groupby('userId').rating.mean().reset_index()

     userId    rating
0         1  3.628319
1         2  3.896552
2         3  3.794521
3         4  4.161290
4         5  3.183824
..      ...       ...
663     664  4.067568
664     665  3.211454
665     666  3.342222
666     667  3.790541
667     668  2.797200

[668 rows x 2 columns]

In [ ]:
users = users.merge(r.groupby('userId').rating.mean().reset_index(), on='userId')

In [ ]:
users

     userId  age  time_spent_per_day    rating
0         1   16            3.976315  3.628319
1         2   24            1.891303  3.896552
2         3   20            4.521478  3.794521
3         4   23            2.095284  4.161290
4         5   35            1.759860  3.183824
..      ...  ...                 ...       ...
663     664   22            5.288101  4.067568
664     665   20            5.220446  3.211454
665     666   19            3.262313  3.342222
666     667   17            3.674356  3.790541
667     668   24            2.718718  2.797200

[668 rows x 4 columns]

In [ ]:
users = users.merge(r.groupby('userId').hour.mean().reset_index(), on='userId')

In [ ]:
users.head(3)

   userId  age  time_spent_per_day    rating       hour
0       1   16            3.976315  3.628319   0.000000
1       2   24            1.891303  3.896552  16.000000
2       3   20            4.521478  3.794521   9.027397

In [ ]:
u = users.copy()
u = u.set_index('userId')
u.columns = ['age', 'time_spent_per_day', 'u_avg_rating', 'hour']

In [ ]:
u

        age  time_spent_per_day  u_avg_rating       hour
userId
1        16            3.976315      3.628319   0.000000
2        24            1.891303      3.896552  16.000000
3        20            4.521478      3.794521   9.027397
4        23            2.095284      4.161290   2.040323
5        35            1.759860      3.183824  19.000000
...     ...                 ...           ...        ...
664      22            5.288101      4.067568  16.027027
665      20            5.220446      3.211454  12.237885
666      19            3.262313      3.342222   8.102222
667      17            3.674356      3.790541  14.729730
668      24            2.718718      2.797200  10.337091

[668 rows x 4 columns]

In [ ]:
scaler = StandardScaler()

In [ ]:
scaler.fit_transform(u)

array([[-1.47029242,  0.34107301, -0.07696514, -1.91196994],
       [-0.13561556, -1.07994746,  0.5116626 ,  0.61457625],
       [-0.80295399,  0.71262375,  0.28775894, -0.48646143],
       ...,
       [-0.9697886 , -0.14554853, -0.70479307, -0.63255502],
       [-1.30345781,  0.13527572,  0.27902496,  0.41398896],
       [-0.13561556, -0.51603068, -1.90082486, -0.2796489 ]])

In [ ]:
u = pd.DataFrame(scaler.fit_transform(u), columns=u.columns, index=u.index)
u.head(2)

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.076965 -1.911970
2      -0.135616           -1.079947      0.511663  0.614576

In [ ]:
u.reset_index()

     userId       age  time_spent_per_day  u_avg_rating      hour
0         1 -1.470292            0.341073     -0.076965 -1.911970
1         2 -0.135616           -1.079947      0.511663  0.614576
2         3 -0.802954            0.712624      0.287759 -0.486461
3         4 -0.302450           -0.940926      1.092622 -1.589784
4         5  1.699565           -1.169532     -1.052393  1.088304
..      ...       ...                 ...           ...       ...
663     664 -0.469285            1.235109      0.886951  0.618844
664     665 -0.802954            1.188999     -0.991760  0.020504
665     666 -0.969789           -0.145549     -0.704793 -0.632555
666     667 -1.303458            0.135276      0.279025  0.413989
667     668 -0.135616           -0.516031     -1.900825 -0.279649

[668 rows x 5 columns]

In [ ]:
m.head()

genres,(no genres listed),Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,,
1,0,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
4,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0
5,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [ ]:
X = ratings[['movieId', 'userId', 'rating']].copy()
X = X.merge(u.reset_index(), on = 'userId', how = 'right')
X = X.merge(m.reset_index(), on = 'movieId', how = 'right')

In [ ]:
X

,movieId,userId,rating,age,time_spent_per_day,u_avg_rating,hour,(no genres listed),Action,Adventure,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,2.0,5.0,-0.135616,-1.079947,0.511663,0.614576,0,0,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5.0,4.0,1.699565,-1.169532,-1.052393,1.088304,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2,1,8.0,5.0,0.364888,0.298545,0.292345,0.456667,0,0,1,...,0,0,0,0,0,0,0,0,0,0
3,1,11.0,4.0,-1.303458,0.513712,-0.301997,-0.422415,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,1,14.0,4.0,-0.302450,1.251552,-0.410805,-0.490788,0,0,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105338,148238,475.0,3.0,-1.136623,1.571992,-0.876863,0.568177,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105339,148626,458.0,4.0,-0.302450,-0.637351,-0.641016,0.191340,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105340,148626,576.0,4.5,-0.469285,-0.266530,0.011718,0.004695,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105341,148626,668.0,4.5,-0.135616,-0.516031,-1.900825,-0.279649,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105342,149532,475.0,4.0,-1.136623,1.571992,-0.876863,0.568177,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105334     668   142488     4.0  1451535844
105335     668   142507     3.5  1451535889
105336     668   143385     4.0  1446388585
105337     668   144976     2.5  1448656898
105338     668   148626     4.5  1451148148

[105339 rows x 4 columns]

In [ ]:
X = X.drop(columns = ['movieId', 'userId'])
y = X.pop('rating')

In [ ]:
X

,age,time_spent_per_day,u_avg_rating,hour,(no genres listed),Action,Adventure,Animation,Children,Comedy,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,-0.135616,-1.079947,0.511663,0.614576,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1.699565,-1.169532,-1.052393,1.088304,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
2,0.364888,0.298545,0.292345,0.456667,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
3,-1.303458,0.513712,-0.301997,-0.422415,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
4,-0.302450,1.251552,-0.410805,-0.490788,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
105338,-1.136623,1.571992,-0.876863,0.568177,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
105339,-0.302450,-0.637351,-0.641016,0.191340,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105340,-0.469285,-0.266530,0.011718,0.004695,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105341,-0.135616,-0.516031,-1.900825,-0.279649,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
105342,-1.136623,1.571992,-0.876863,0.568177,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
y

0         5.0
1         4.0
2         5.0
3         4.0
4         4.0
         ...
105338    3.0
105339    4.0
105340    4.5
105341    4.5
105342    4.0
Name: rating, Length: 105343, dtype: float64

In [ ]:
X = X.dropna()

In [ ]:
y = y.dropna()

In [ ]:
X.shape

(105339, 24)

In [ ]:
y.shape

(105339,)

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

## You can use your favourite algorithm

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

## Boosting , then no need to scale

In [ ]:
from sklearn.ensemble import GradientBoostingRegressor

In [ ]:
model = GradientBoostingRegressor()

In [ ]:
model.fit(X_train, y_train)

GradientBoostingRegressor()

In [ ]:
y_pred_train = model.predict(X_train)

In [ ]:
mse(y_train, y_pred_train)**0.5

0.908935888692867

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
y_pred

array([4.080252  , 3.3586443 , 3.5280851 , ..., 3.36528732, 3.1743079 ,
       3.17728457])

In [ ]:
from sklearn.metrics import mean_squared_error as mse

In [ ]:
mse(y_test, y_pred)**0.5

0.9118203864287907

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

In [ ]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [ ]:
y_pred_train = rf.predict(X_train)

In [ ]:
mse(y_train, y_pred_train)**0.5

0.6578080661191699

In [ ]:
mse(y_test, y_pred)**0.5

0.9568230456144132

In [ ]:
ratings.loc[ratings.userId == 1].head()

In [ ]:
model.predict()

## Matrix Factorisation from scratch

In [ ]:
ratings.head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [ ]:
ratings = ratings.pivot(index='userId', columns='movieId', values='rating').fillna(0)

In [ ]:
rm = ratings

In [ ]:
rm.shape

(668, 10325)

In [ ]:
((rm >0).sum().sum())/(rm.shape[0]*rm.shape[1])

np.float64(0.015272940801206305)

In [ ]:
rm

movieId,1,2,3,4,5,6,7,8,9,10,...,144482,144656,144976,146344,146656,146684,146878,148238,148626,149532
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,3.0,3.0,2.0,0.0,2.5,5.0,3.0,0.0,0.0,3.5,...,0.0,0.0,2.5,0.0,0.0,0.0,0.0,0.0,4.5,0.0

In [ ]:
rm_small = rm.copy()

In [ ]:
rm_small = rm_small[rm_small.columns[:100]]

In [ ]:
rm_small = rm_small.head(100)

In [ ]:
rm_small

movieId,1,2,3,4,5,6,7,8,9,10,...,100,101,102,103,104,105,107,108,110,111
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0
2,5.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,5.0,0.0,4.0,0.0,3.0,4.0,3.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,3.0,0.0,0.0,0.0
97,3.5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## MF From scratch

In [ ]:
rm_small.shape

(100, 100)

In [ ]:
K = 2

P = np.random.normal(size = (100,2))

Q = np.random.normal(size = (100,2))

In [ ]:
P.shape

(100, 2)

In [ ]:
def matrix_factorization(R, P, Q, K, steps=10000, alpha=0.0002, beta=0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] == 0:
                    continue
                eij = R[i][j] - np.dot(P[i,:],Q[:,j])
                for k in range(K):
                    x = P[i][k]
                    P[i][k] += alpha * (2 * eij * Q[k][j]) # - beta * P[i][k])
                    Q[k][j] += alpha * (2 * eij * x) # - beta * Q[k][j])

    return P,Q.T

In [ ]:
P_, Q_  = matrix_factorization(rm_small.values.copy(), P.copy(), Q.copy(), 2)

In [ ]:
rm_small.values[1,0]

np.float64(5.0)

In [ ]:
np.dot(P_[1], Q_[0])

np.float64(4.690705359304236)

In [ ]:
print(np.dot(P_[1], Q_[2]), rm_small.values[1, 2])

3.4832040343302593 2.0

In [ ]:
rm_small

In [ ]:
np.dot(P_, Q_.T)

array([[ 3.99474837,  3.1462978 ,  2.84536603, ..., -0.73425837,
         4.02351549,  4.08779127],
       [ 4.69070536,  2.4621531 ,  3.48320403, ..., -0.20268709,
         5.39187475,  4.21144332],
       [ 5.21437515,  4.07454313,  3.71780797, ..., -0.94112367,
         5.26944169,  5.32037834],
       ...,
       [ 5.80268301, -0.87441709,  4.76106813, ...,  1.84729349,
         8.7932275 ,  3.33757732],
       [ 3.58140909,  2.43693216,  2.59522102, ..., -0.45287431,
         3.81506955,  3.48152208],
       [ 3.08219791,  7.45363644,  1.61570252, ..., -3.25636789,
         0.38233768,  5.5543348 ]])

In [ ]:
abs(np.dot(P_, Q_.T) - rm_small)

movieId,1,2,3,4,5,6,7,8,9,10,...,100,101,102,103,104,105,107,108,110,111
userId,,,,,,,,,,,,,,,,,,,,,
1,3.994748,3.146298,2.845366,1.011652,2.459722,4.063306,2.465751,2.151184,1.848379,3.432234,...,1.448672,2.921224,1.726941,1.081833,3.306684,2.731602,2.659577,0.734258,0.023515,4.087791
2,0.309295,2.462153,1.483204,0.307919,0.199853,5.148531,3.142002,2.101684,2.640309,4.487246,...,2.082307,2.394055,2.699655,1.550469,3.680213,3.873182,3.634131,0.202687,5.391875,4.211443
3,5.214375,4.074543,3.717808,1.297421,0.218872,5.313768,0.225038,2.796821,2.425036,4.492117,...,1.900969,3.785901,2.271822,1.419478,4.310923,0.583052,3.484984,0.941124,5.269442,5.320378
4,0.939642,7.150324,0.070033,4.815553,1.042363,1.007043,0.703179,2.713040,2.009657,1.570233,...,1.642476,6.076829,3.088698,1.202907,1.831470,2.820322,2.033675,3.603337,2.525303,0.022933
5,0.020738,9.387673,2.113088,5.473437,0.868869,2.132719,1.204384,4.295939,0.543471,1.099481,...,0.491701,8.167863,1.689239,0.344114,4.321785,0.657195,0.055006,4.078185,0.121062,7.058522
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,0.499972,3.986617,0.845754,1.455501,0.341015,0.441809,0.310915,2.575581,0.913488,3.702294,...,1.495051,3.662648,1.704199,1.118100,0.202355,2.838148,0.187532,1.063871,4.292859,4.816100
97,0.003572,0.000790,2.352526,1.772587,1.843790,3.184086,1.914403,2.313533,1.148349,2.550393,...,0.886986,3.604431,0.838676,0.666954,3.103894,1.726009,1.818257,1.307473,2.857361,4.177262
98,5.802683,0.874417,4.761068,2.418554,4.949707,7.569415,4.671579,1.250174,4.761134,7.005009,...,3.788801,0.334530,5.476976,2.809294,0.091740,6.909093,6.121931,1.847293,8.793227,3.337577
99,3.581409,2.436932,2.595221,0.632891,2.302267,3.760397,2.287448,1.796452,1.803487,3.219456,...,1.417524,2.296253,1.757512,1.057156,2.901450,2.656300,2.543613,0.452874,3.815070,3.481522
100,0.082198,7.453636,1.615703,4.369695,0.626905,1.596119,0.896388,3.390241,0.490459,0.784015,...,0.437246,6.479795,1.407801,0.307978,3.377465,0.607504,0.033008,3.256368,0.382338,5.554335

In [ ]:
rm_small.values[rm_small>0]

array([4. , 1.5, 4. , 4. , 4. , 4. , 5. , 2. , 3. , 4. , 5. , 3. , 3. ,
       5. , 4. , 4. , 5. , 4. , 4. , 3. , 3. , 4. , 5. , 5. , 4. , 4. ,
       5. , 5. , 3. , 4. , 5. , 4. , 4. , 3. , 0.5, 4. , 5. , 5. , 4.5,
       5. , 4. , 3. , 5. , 3. , 5. , 5. , 3. , 4. , 4. , 3. , 3. , 3. ,
       3. , 4. , 3. , 3. , 4. , 2. , 3. , 3. , 4. , 3. , 3. , 2. , 2. ,
       3. , 3. , 3. , 5. , 4. , 3. , 3. , 3. , 3. , 2. , 2. , 4. , 3. ,
       1.5, 3.5, 4. , 4.5, 4. , 3. , 3. , 3. , 5. , 3. , 3. , 5. , 5. ,
       3. , 4. , 3. , 5. , 5. , 5. , 4. , 5. , 5. , 5. , 1.5, 3. , 1.5,
       4.5, 4.5, 3.5, 2.5, 2.5, 3.5, 2.5, 4.5, 4.5, 2.5, 3.5, 4. , 4. ,
       4. , 5. , 3. , 5. , 2. , 5. , 5. , 2. , 2. , 2. , 4. , 1. , 1. ,
       3. , 4. , 2.5, 2. , 3. , 3. , 4. , 5. , 4. , 4. , 1. , 2. , 4. ,
       4. , 4. , 2. , 3. , 4. , 3. , 3. , 3. , 3. , 3. , 3. , 4. , 3. ,
       3. , 3. , 4. , 1. , 3. , 1. , 4. , 3. , 4. , 3. , 2. , 3. , 3. ,
       2. , 3. , 4. , 3. , 2. , 3. , 4.5, 4. , 4. , 4. , 4. , 4. , 4. ,
       5. , 4. , 4. , 5. , 4. , 5. , 4. , 4. , 3. , 4. , 5. , 4. , 4. ,
       5. , 5. , 3. , 3. , 3. , 5. , 1. , 2. , 5. , 3. , 4. , 5. , 5. ,
       3.5, 5. , 2. , 3. , 3.5, 4.5, 3.5, 4. , 2. , 2.5, 3. , 5. , 4.5,
       4. , 5. , 1.5, 5. , 5. , 0.5, 4. , 1.5, 4. , 3. , 4. , 4. , 1.5,
       4. , 2. , 5. , 4. , 4. , 4. , 4. , 3. , 5. , 3. , 3. , 5. , 4. ,
       5. , 5. , 5. , 3. , 5. , 3. , 3. , 3. , 5. , 4. , 0.5, 4. , 3. ,
       3. , 5. , 3. , 2. , 4. , 5. , 5. , 3. , 2. , 4. , 3. , 4. , 2.5,
       4. , 1. , 2.5, 4. , 1. , 5. , 4.5, 5. , 3.5, 3. , 2. , 4. , 4.5,
       4. , 4.5, 4. , 3.5, 4.5, 0.5, 2.5, 2. , 1.5, 1. , 3.5, 4.5, 4.5,
       0.5, 2. , 2. , 3.5, 5. , 1. , 3.5, 0.5, 0.5, 1.5, 0.5, 3.5, 4. ,
       3. , 0.5, 1.5, 0.5, 0.5, 2.5, 0.5, 0.5, 3.5, 0.5, 3. , 2. , 3. ,
       3.5, 3. , 2.5, 4. , 3.5, 3. , 2.5, 4. , 4. , 4.5, 2. , 3. , 4. ,
       4. , 4. , 5. , 4. , 4. , 1. , 2. , 4. , 3. , 4. , 4. , 2. , 2. ,
       3. , 2.5, 5. , 4. , 4.5, 3. , 3.5, 5. , 2.5, 5. , 4.5, 3. , 2. ,
       5. , 4. , 4.5, 4.5, 4.5, 4. , 4. , 5. , 3. , 3. , 1. , 4. , 4. ,
       3. , 4. , 4. , 4. , 3. , 1. , 2. , 2. , 2. , 5. , 1.5, 5. , 3.5,
       4. , 3.5, 2. , 3. , 4. , 4. , 4.5, 3. , 3.5, 4. , 4.5, 3.5, 4. ,
       3.5, 1.5, 3.5, 3. , 3.5, 3. , 3.5, 5. , 3. , 5. , 4.5, 2.5, 4. ,
       4.5, 3.5, 3.5, 2.5, 3.5, 3.5, 4.5, 4.5, 4.5, 4.5, 3.5, 4. , 3.5,
       2.5, 4.5, 5. , 5. , 4.5, 3. , 3.5, 5. , 5. , 2.5, 4.5, 3.5, 3. ,
       4. , 4. , 4. , 2. , 4. , 4. , 3.5, 3.5, 3. , 3. , 4. , 3.5, 2. ,
       3.5, 2.5, 3.5, 4. , 3.5, 3. , 3. , 4. , 4. , 3. , 4. , 5. , 5. ,
       2. , 4. , 3. , 3. , 3. , 3. , 5. , 3. , 4. , 4. , 5. , 3. , 1. ,
       3. , 2. , 4. , 2. , 3. , 3. , 5. , 4. , 3. , 4. , 3. , 1. , 3. ,
       2. , 3. , 5. , 1. , 4. , 5. , 3. , 3. , 3. , 4. , 3. , 3.5, 4. ,
       3. , 1. , 4. , 3. , 5. ])

In [ ]:
rm_ = np.dot(P_, Q_.T)

In [ ]:
mse(rm_small.values[rm_small > 0], rm_[rm_small > 0])**0.5

0.5638272090423415

In [ ]:
!pip install cmfrec

Collecting cmfrec
  Downloading cmfrec-3.5.1.post13.tar.gz (268 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.5/268.5 kB 3.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cython in /usr/local/lib/python3.12/dist-packages (from cmfrec) (3.0.12)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from cmfrec) (2.0.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from cmfrec) (1.16.3)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from cmfrec) (2.2.2)
Collecting findblas (from cmfrec)
  Using cached findblas-0.1.26.post1-py3-none-any.whl
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->cmfrec) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->cmfrec) (1.17.0)
Building wheels for collected packages: cmfrec
  Building wheel for cmfrec (pyproject.toml) ... done
  Created wheel for cmfrec: filename=cmfrec-3.5.1.post13-cp312-cp312-linux_x86_64.whl size=5975865 sha256=b437f3d27853eaffc75f55eb043a5c8d745bf52cda5b244f07f45ae79bb8cb78
  Stored in directory: /root/.cache/pip/wheels/46/9d/a7/03614a1633b40dde9aeb6eb12265f9c684feba1e3d82fe05bf
Successfully built cmfrec
Installing collected packages: findblas, cmfrec
Successfully installed cmfrec-3.5.1.post13 findblas-0.1.26.post1

In [ ]:
ratings

movieId,1,2,3,4,5,6,7,8,9,10,...,144482,144656,144976,146344,146656,146684,146878,148238,148626,149532
userId,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,5.0,0.0,2.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
664,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
665,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
666,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
667,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
668,3.0,3.0,2.0,0.0,2.5,5.0,3.0,0.0,0.0,3.5,...,0.0,0.0,2.5,0.0,0.0,0.0,0.0,0.0,4.5,0.0

In [ ]:
rm_small.columns

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
        29,  30,  31,  32,  33,  34,  35,  36,  39,  40,  41,  42,  43,  44,
        45,  46,  47,  48,  49,  50,  52,  53,  54,  55,  57,  58,  59,  60,
        61,  62,  63,  64,  65,  66,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        92,  93,  94,  95,  96,  97, 100, 101, 102, 103, 104, 105, 107, 108,
       110, 111],
      dtype='int64', name='movieId')

In [ ]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()

KeyError: "None of [Index(['userId', 'movieId', 'rating'], dtype='object', name='movieId')] are in the [columns]"

In [ ]:

rm_raw.columns = ['UserId', 'ItemId', 'Rating']

KeyError: "None of [Index(['userId', 'movieId', 'rating'], dtype='object', name='movieId')] are in the [columns]"

In [ ]:
from cmfrec import CMF

In [ ]:
model = CMF(method = 'als', k = 2, lambda = 0.1, user_bias = False, item_bias = False)

SyntaxError: invalid syntax (ipython-input-596754825.py, line 1)

In [ ]:
model.fit(rm_raw)

In [ ]:
model.A_.shape

In [ ]:
model.B_.shape

AttributeError: 'GradientBoostingRegressor' object has no attribute 'B_'

In [ ]:
model.global_mean_